---
title: "Campañas y zonas implementadas en CampR 0.6.0"
author: "Fran Velasco"
package: CampR
date: "`r Sys.Date()`"
output: rmarkdown::html_document
vignette: >
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteINdexEntry{Campañas y zonas implementadas en CampR 0.8.8} 
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE, results='hide',include=FALSE}
library(CampR)
```

 Mapa Demersales 
---------------


```{r SP-NORT, fig.width=7.2,fig.height=3.8}
MapNort()
```

### Resumen campaña Demersales

```{r SP-NORT results, fig.width=7.2,fig.height=3.8}
armap.camp("N07","Cant",ti=T,es=T)
```

 Mapa del Banco de Porcupine
---------------


```{r SP-PORC, fig.width=7.2,fig.height=3.8}
mapporco()
```

### Resumen campaña Porcupine

```{r Porcupine, fig.width=6,fig.height=4.7}
par(mfrow=c(1,2))
armap.camp("P07","Porc",ti=T)
armap.camp("P07","Porc",ti=F,CTD=T,lans=F)
```

 Mapa Golfo de Cádiz 
---------------

```{r SP-ARSA, fig.width=7.2,fig.height=3.8}
MapArsa()
```

### Resumen campaña Arsa
```{r Arsa resultaos, fig.width=6.2,fig.height=5.1}
armap.camp("207","Arsa",ti=T,es=T)
```

 Mapa del Mediterráneo
---------------

```{r Medits, fig.width=7.2,fig.height=6.4}
MapMedit()
```

### Resumen campaña Medits
```{r Medits-result, fig.width=6.4,fig.height=6.4}
armap.camp("M07","Medi",ti=T,es=T)
```

 Mapa de la Península Ibérica con FUs cigala
---------------
### Resumen Unidades funcionales Iberoatlánticas 
```{r IbAtlFUs, fig.width=7.2,fig.height=6.4}
MapIberia(xlims = c(-10.5, -1.1), ylims = c(35.95, 44.52),places = T,pais=F,
          FU=c("FU31","FU25","FU26","FU27","FU39","FU30"),ColFU = "white")
text(-9.5,42.5,"FU26",font=2,col=1,cex=1)
text(-9.5,40.5,"FU27",font=2,col=1,cex=1)
text(-5,44,"FU31",font=2,col=1,cex=1)
text(-9.5,43.5,"FU25",font=2,col=1,cex=1)
text(-6.8,36.5,"FU30",font=2,col=1,cex=1)
```
