---
title: "Vignette 2.-Instalación de librerías para CampR"
author: "Fran Velasco"
date: "`r Sys.Date()`"
output: html_document
vignette: |
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteIndexEntry{Vignette 2.-Instalación de librerías para CampR}  
  %\VignetteEncoding{UTF-8}
---

### <div style="text-align: center">  CampR: Instalación de R, Rstudio y librerías de R necesarias </div>

------------

La librería CampR importa funciones de muchas otras librerías, pero dadas las limitaciones de tener que trabajar en 32bits en lugar de 64bits hay que tener en cuenta que la librería CampR funciona con R en 32bits, no con R en 64bits, con lo que:

- [R tiene que ser R 3.6.3](https://cran.r-project.org/bin/windows/base/old/3.6.3/) y escoger la versión de 32 bits en el Rstudio
- [RStudio 1.1.463.exe](https://s3.amazonaws.com/rstudio-dailybuilds/RStudio-1.1.463.exe)
- [Rtools35.exe](https://cran.r-project.org/bin/windows/Rtools/Rtools35.exe) o [Rtools40-x86_64.exe](https://cran.r-project.org/bin/windows/Rtools/rtools40-x86_64.exe) 

Además hay algunas librerías que han pasado a versiones modernas que no son compatibles con 32bits, por ello hay que instalar algunas librerías en versiones antiguas, entre ellas están:

* cli 2.5.0
* data.table 1.11
* dplyr 1.0.6
* glue 1.3.2
* lattice 0.20-38
* magrittr 1.5
* pillar 1.5.1
* rlang 0.4.10
* ggplot2 3.4.0
* tibble 2.1.3
* tidyselect (<= 1.1.0)
* vctrs 0.3.5
* maptools 1.1-4
* rgdal 1.5-32
* ggplot2 3.4.0
* RODBC 1.3-16  (En principio ya no es necesario)


Para instalar estas librerías en la versión adecuada se puede utilizar el comando remotes::install_version("librería","versión")
un Script adeduado una vez desinstaladas versiones anteriores de las librerías incluidas en el script sería:

```{r}
#' remotes::install_version("cli","3.4.0",dependencies = F)
#' remotes::install_version("glue","1.3.2",dependencies = F)
#' remotes::install_version("lifecycle","1.0.3",dependencies = F)
#' remotes::install_version("magrittr","1.5",dependencies = F)
#' remotes::install_version("vctrs","0.5.2",dependencies = F)
#' remotes::install_version("pillar","1.5.1",dependencies = F)
#' remotes::install_version("rlang","1.0.6",dependencies = F)
#' remotes::install_version("ggplot2","3.4.0",dependencies=F)
#' remotes::install_version("tibble","2.1.3",dependencies = F)
#' remotes::install_version("tidyverse","1.3.0",dependencies = F)
#' remotes::install_version("tidyselect","1.2.0",dependencies = F)
#' remotes::install_version("dplyr","1.1.0",dependencies = F)

```

#### Otras librerías utilizadas en CampR

Hay otras librerías de las que se utilizan funciones en CampR:

- Manejo de datos y bases de datos:
  - DBI
  - odbc
  - foreign
  - tidyverse

- mapas y fechas:
  - maps
  - mapdata
  - suncalc
  - geosphere

- graficos:
  - lattice
  - grid
  - gstat

- estadística mates y otras:
    - boot
    - worrms
    - vegan
    - icesDatras
    - hablar
