---
title: "Vignette 4.- CampR con plotly y ggplot2"
author: "Fran Velasco"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
vignette: |
  %\VignetteEngine{knitr::rmarkdown} 
  %\VignetteIndexEntry{Vignette 4.- CampR con plotly y ggplot2} 
  %\VignetteEncoding{UTF-8}
---

Crear mapas de CampR con ggplot2. 

```{r load library, message=FALSE, warning=FALSE, include=FALSE}
library(ggplot2)
library(CampR)
library(plotly)
# library(RColorBrewer)
# yor_col<- brewer.pal(7, "Greens")
```

La función ggplot2::map_data permite dar formato a Porc.map para pintarlo con ggplot2


```{r Data}
Porc<-ggplot2::map_data(Porc.map) 
head(Porc)
hake<-CampR::maphist(1,50,"P16","Porc",out.dat=T,plot=F)
```

```{r Graf Porcupine}
p<-ggplot2::ggplot(hake)+
  geom_polygon(aes(long,lat,group=group),data=Porc,fill="white",color="darkgrey")+
  geom_point(aes(x=long,y=lat,size=sqrt(numero),text=lan),color="blue")+
  scale_size_continuous(name="No. ind.")+coord_fixed(1.3)
ggplotly(p,tooltip=c("text","lance"),width=800,height=500)
```
```{r resultados tabla}
library(knitr)
library(kableExtra)
options(knitr.table.format = "markdown") 
kable(databICES(1,50,"N16","Cant"),digits=2,caption="Merluza en 2016 Cantábrico y Galicia") %>%
  kable_styling(bootstrap_options="condensed",full_width=F,position="center")
```

```{r Demersales datos}
Nort<-ggplot2::map_data(Nort.map)
head(Nort)
```

```{r mapas Demersales}
ggplot2::ggplot(data=Nort)+geom_polygon(aes(long,lat,fill=region,group=group),col="white")+
  coord_fixed(1.3)
```

